<?php

namespace AppBundle\Repository;

/**
 * FurtherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurtherRepository extends \Doctrine\ORM\EntityRepository
{
}
