<?php

namespace AppBundle\Repository;

/**
 * HouseOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
