<?php

namespace AppBundle\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
